### ISSUE TITLE
ruoyi4.5.6版本连接不上冰蝎马但能执行命令

### ISSUE THREAD

**Issue by SummerSec** [lz2y/yaml-payload-for-ruoyi#3]
![image](https://user-images.githubusercontent.com/47944478/145924407-0cf78412-3c06-4d30-9244-2912f52d92d9.png)

直接执行命令
![image](https://user-images.githubusercontent.com/47944478/145924419-de27b4e2-4acd-445a-9d44-04ed93928fba.png)

连接冰蝎马失败
![image](https://user-images.githubusercontent.com/47944478/145924448-700b7b7e-cb46-4991-8e8c-b1cb921d3e91.png)

![image](https://user-images.githubusercontent.com/47944478/145924465-a3368613-841e-4e3f-b845-9d9c9c732d6f.png)

**Comment by lz2y** [comment]
师傅好，尝试修改url为 `/login?cmd=1` 或者带上cookie后在其他路径使用。没登陆的话他会跳转到 /login

**Comment by SummerSec** [comment]
> 师傅好，尝试修改url为 `/login?cmd=1` 或者带上cookie后在其他路径使用。没登陆的话他会跳转到 /login

成功了，谢谢师傅。
